sentimentfiles/apple/urls.py
#from django.conf.urls import url, include
from django.urls import path, include
from . import views

app_name = 'apple'
urlpatterns = [
    #url(r'^', views.home, name="home"),
    path('home/', views.home, name="home"),
    # path('', views.index, name="index"),
    path('newpage/',  views.new_page,  name="my_function"),
    path('register/',views.register, name="register"),
    path('user_login/',views.user_login, name="user_login"),
   
    
]

sentimentfiles/sentimentfiles/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apple import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^apple/', include('apple.urls')),
    url(r'^special/',views.special,name='special'),
    url(r'^logout/$', views.user_logout, name='logout'),

]
    

sentimentfiles/apple/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


class Review(models.Model):
    text = models.CharField(max_length=300)
    value = models.CharField(max_length=50)

sentimentfiles/apple/forms.py
from django import forms
from apple.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

sentimentfiles/apple/views.py
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from django.shortcuts import render


from apple.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Review

# import tweepy
# from textblob import TextBlob
import pandas as pd
import numpy as np
# import pickle
from sklearn.model_selection import train_test_split


df = pd.read_csv('tweets.csv')


text = df['tweet_text']

target = df['is_there_an_emotion_directed_at_a_brand_or_product']

#print(len(text))

target = target[pd.notnull(text)]
text = text[pd.notnull(text)]


count_vect = CountVectorizer()
count_vect.fit(text)
l_count = len(count_vect.vocabulary_)
#print(count_vect.vocabulary_)
counts = count_vect.transform(text)
#print(counts)


nb = MultinomialNB()
nb.fit(counts, target)


# split into train and test sets
x_train, x_test, y_train, y_test = train_test_split(
    counts, target, train_size=0.80, test_size=0.20, random_state=0)

nb = MultinomialNB()
nb.fit(x_train, y_train)

y_predicted = nb.predict(x_test)
print(y_predicted)
#print(x_train, y_train)
#print(x_test, y_test)

#accuracy = accuracy_score(y_test, y_predicted)
accuracy = accuracy_score(y_test, y_predicted)

confuse = confusion_matrix(y_test, y_predicted)
print(confuse)


report = classification_report(y_test, y_predicted)
print(report)


def home(request):
    sentiment = nb.predict(count_vect.transform(["I hate iphones"]))

    context = {'sentiment': sentiment, 'accuracy': accuracy,
               'confuse': confuse, 'report': report, 'counts': l_count}
    #sentiment = nb.predict(count_vect.transform(['I hate my iphone']))
    return render(request, 'apple/home.html', context)


def new_page(request):
    data = request.GET['fulltextarea']
    print(nb.predict(count_vect.transform([data])))
    sentiment = nb.predict(count_vect.transform([data]))

    review = Review()
    review.text = data
    review.value = sentiment
    review.save()

    context = {'sentiment': sentiment, 'accuracy': accuracy,
               'confuse': confuse, 'data': data, 'report': report, 'counts': l_count}

    return render(request, 'apple/display.html', context)


def index(request):
    return render(request, 'apple/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'apple/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'apple/login.html', {})

sentimentfiles/apple/templates/apple/base.html
{% load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                {# Django Home Link / Admin Link / Register Link#}
                <li><a class="navbar-brand" href="{% url 'index' %}">Hexia Classifier</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin dashboard</a></li>
                {# Some logic on what to display for last item#}
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'apple:home' %}">Main Feature</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'apple:user_login' %}">Login</a></li>
                <li><a class="navbar-link" href="{% url 'apple:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

sentimentfiles/apple/templates/apple/display.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>

        body{
          width: 1000px;
          margin: auto;
          
        }
      </style>
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'apple:home' %}">Home Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'apple:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Raw Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
          </ul>
          <span class="navbar-text">
            Navbar text with an inline element
          </span>
        </div>
      </nav>

    <div class="modal">  
            <h1>HOMEPAGE</h1>
      <a href="{% url 'apple:home' %}"> Go Back</a>
    
    </div>

    <div>
        <p> The original Text</p>
      <p >{{data}} </p>
      <p> The Sentiment Value is : {{sentiment}}</p>
      
      <div class="container px-lg-5">
        <div class="row mx-lg-n5">
          <div class="col py-3 px-lg-5 border bg-light">
            <p>Number of Instances : {{counts}}</p>
          </div>
          <div class="col py-3 px-lg-5 border bg-light">
            <p> Accuracy Level : {{accuracy |floatformat:2}}</p>
           
          </div>
        </div>
      </div>
   
     <!-- <br>
     <p> Confusion Matrix : {{confuse}}</p>
    
     <br>
     <p style="text-align: center;"> <strong> Classification Report : {{report}}</strong> </p>
    
     <br> -->
       
        
    </div>

  </body>
</html>

sentimentfiles/apple/templates/apple/home.html
{%load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  

  <style>
    body {
      width: 800px;
      margin: auto;
    }
    textarea {
    display: block;
    margin-left: auto;
    margin-right: auto;
}



  </style>
  <title>HEXIA</title>
</head>

<body>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'apple:home' %}">HEXIA SENTIMENT ANALYZER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
      aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        <li><a class="navbar-link" href="{% url 'apple:home' %}">Main Feature</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a class="navbar-link" href="{% url 'apple:user_login' %}">Login</a></li>
        <li><a class="navbar-link" href="{% url 'apple:register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <h1 style="align-self: center;"> Sentiment Anlaysis on Electronic Gadgets</h1>

  <div class="square">


    <form action="{% url 'apple:my_function' %}">
      <textarea name="fulltextarea" cols="70" rows="5"></textarea>
      <br />
      <input type="submit" style="margin:0px auto; display:block;" class="btn btn-primary" value="Submit" />


    </form>

  </div>


  <div>
    <div class="container">
      <!-- <div class="row">
        <div class="col-sm">
          One of three columns
        </div>
        <div class="col-sm">
          One of three columns
        </div>
        <div class="col-sm">
          One of three columns
        </div>
      </div> -->
    </div>
    <hr>
<br>
    <div class="container px-lg-5">
      <div class="row mx-lg-n5">
        <div class="col py-3 px-lg-5 border bg-light">
          <p>Number of Instances : {{counts}}</p>
        </div>
        <div class="col py-3 px-lg-5 border bg-light">
          <p> Accuracy Level : {{accuracy |floatformat:2}}</p>
         
        </div>
      </div>
    </div>
    <br>
    {{data}}

    <br>


    <br>




  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

sentimentfiles/apple/templates/apple/index.html
{% extends "apple/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1 style="text-align: center;">Welcome!</h1>
        {% if user.is_authenticated %}
        <h2>Logged in as {{ user.username }}</h2>
        <h3 style="text-align: center;">Abstract</h3>
        <p>The emergence of online marketplaces has contributed to the increase in the 
            number of consumers for a product. It also provides an avenue for consumers
             to give instant feedback from the purchased product. In as much as good
              feedback helps to attract more sales, a bad consumer experience can affect sales 
              as well. In other words, analysis of consumer sentiment with quickly appropriate 
              response helps to save the business of the day. In this report, a study on sentiment 
              analysis is conducted to assess the opinion of consumers regarding electronic
               gadgets that are considered niche products for online marketplaces. 
               By exploring machine learning algorithms, the algorithm that gives more accurate result
                is chosen. The trained model is then used to analyze real-time reviews and comments about 
                these products. The system works by accepting input text from the user, performs sentiment
                 analysis operations, and give results. The system is based on a sentiment analysis algorithm
                  to quantify positive and negative feelings concerning iPhone and android devices.  </p>
        {% else %}
        <h2>Register or Login if you'd like to</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

sentimentfiles/apple/templates/apple/login.html
{% extends 'apple/base.html' %}
{% block body_block %}
<div class="container" style="width: 50%;">
    <div class="jumbotron">
        <h2>Login here :</h2>
        <form method="post" action="{% url 'apple:user_login' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password">
            </div>
            <input type="submit" name="" class="btn btn-primary" value="Login">
        </form>
    </div>
</div>



{% endblock %}

sentimentfiles/apple/templates/apple/rawdata.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <style>

        body{
          width: 800px;
          margin: auto;
        }
      </style>
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Raw Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
          </ul>
          <span class="navbar-text">
            Navbar text with an inline element
          </span>
        </div>
      </nav>
    <h1 style="align-self: center;"> Sentiment Anlaysis on Electronic Gadgets</h1>

 

    <div>
      <br>
         {{rdata}}
        
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

sentimentfiles/apple/templates/apple/registration.html
{% extends "apple/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Just fill out the form.</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="form-group">
        {{ user_form.as_p }}
      </div>
      <div class="form-group">
      {{ profile_form.as_p }}
    </div>
      <input type="submit" name="" value="Register">
    </form>

    {% endif %}
  </div>
</div>
{% endblock %}